version: '3.3'
services:
  app:
    container_name: app
    build: .
    command: ["/app/wait-for-it.sh", "redis:6379", "--", "yarn", "dev"]
    ports:
      - "4000:4000"
    depends_on:
      - redis
    links:
      - redis
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
